### ISSUE TITLE
Standalone Demo (Doesn't Work)

### ISSUE THREAD

**Issue by jamiejackson** [epiclabs-io/docker-cucumber-protractor-chrome#5]
I don't understand why this works:

```sh
docker run \
  --volume /tmp/testproj/example:/tests \
  epiclabs/e2e-test-runner \
  --specs /tests/features/google.feature
```

But this doesn't:
```sh
docker run \
  epiclabs/e2e-test-runner \
  --specs /src/example/features/google.feature
```

The image has the source code in already (in `/src`) so why doesn't this work? Is there something magical about the `/tests` path?

It would be convenient to be able to demo this image without having to git clone first.

**Comment by jamiejackson** [comment]
This works, but as you can see, it's convoluted:
```sh
docker run -it --rm \
  --entrypoint '' \
  epiclabs/e2e-test-runner \
  bash -c "mv /src/example/features /tests && /src/protractor.sh"
```

**Comment by aescarcha** [comment]
Hi @jamiejackson, thanks for the feedback, I'll look into it

**Comment by aescarcha** [comment]
After looking at the code, I see that the volume mount is required. Cloning of the repository is not required, but you need a directory with the `features` and `step_definitions`.

The `/tests` path is hardcoded in `protractor.conf.js`. That's where protractor will look for the specs and step_sefinitions.

I know it's a bit redundant because the tests are already inside the image, maybe we could copy the tests there and overwrite the dir if a volume is mounted. I'll check if that's possible using Docker

**Comment by aescarcha** [comment]
Now just running `docker run epiclabs/e2e-test-runner` should execute the default tests, please verify.

**Comment by mogwaipr** [comment]
You do need the volume mount in order to be able to specify where it is going to read the feature and steps from.  
Álvaro, I am trying to add cucumber-protractor-steps to the mix but it always breaks loading the page object files.  Have you tried adding pre-defined Guerkin steps?  I think marketionist has a useful library that I think would help.  (Maybe you've tried adding it already and weren't lucky?)

**Comment by mogwaipr** [comment]
can someone close the non-issue?

**Comment by aescarcha** [comment]
Hi @mogwaipr I haven't tried adding pre-defined steps, had no need for it... but it'd be great if you managed it and made a PR :) closing.

**Comment by mogwaipr** [comment]
> Hi @mogwaipr I haven't tried adding pre-defined steps, had no need for it... but it'd be great if you managed it and made a PR :) closing.

we added it yesterday. still testing it to see how brittle it is. I am also new to Docker so before I publish the repo, I am still learning how to make it a child of your image.  I don't want to publish anything losing link to your repo  ..  

how do you manage to have so many feature scenarios?  I mean, if everybody writes their own steps without consensus, don't you think that it would take a lot of time just rewriting them in order to get glued?  do you use it just for your own test scenarios? You know Gherkin is supposedly meant for QA's to own with the business.  sometimes we are also QA I guess.  I am curious on how to tame the eventual beast of maintaining those scenarios and the assertions made.  I feel it would help to delimit the way they write each line.  Also page object is also important as application elements in the DOM change.  maybe It is ideal to have QA's write the Gherkin and the developers maintain the expected page object elements of the DOM.
